version: "3"

services:
  spotifypulsed:
    build: .
    network_mode: "host"
    environment:
      - PULSE_SERVER=unix:/tmp/pa_containers.socket
      - PULSE_COOKIE=/tmp/pa_containers.cookie
    volumes:
      - "${CONFIG_PATH}/spotifyd.conf:/etc/spotifyd.conf"
      - type: bind
        source: "/tmp/pa_containers.socket"
        target: "/tmp/pa_containers.socket"
    restart: unless-stopped
    user: ${MY_UID}:${MY_GID}
